#pragma config(Sensor, in1,    LINE_L,         sensorReflection)
#pragma config(Sensor, in2,    LINE_C,         sensorReflection)
#pragma config(Sensor, in3,    LINE_R,         sensorReflection)
#pragma config(Sensor, in4,    WRIST_POT,      sensorPotentiometer)
#pragma config(Sensor, in6,    GYRO,           sensorGyro)
#pragma config(Sensor, dgtl1,  QUAD_R,         sensorQuadEncoder)
#pragma config(Sensor, dgtl3,  QUAD_L,         sensorQuadEncoder)
#pragma config(Sensor, dgtl5,  LIFT_ENC,       sensorQuadEncoder)
#pragma config(Sensor, dgtl8,  ULTRA,          sensorSONAR_cm)
#pragma config(Motor,  port1,           DRIVE_FR,      tmotorVex393_HBridge, openLoop, reversed)
#pragma config(Motor,  port2,           DRIVE_BR,      tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port3,           DRIVE_FL,      tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port4,           DRIVE_BL,      tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port6,           CLAW,          tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port8,           LIFT_L,        tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port9,           LIFT_R,        tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port10,          WRIST,         tmotorVex393_HBridge, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#define   PRACTICE // If not defined, then competition mode
#include "definitions.c"
#include "declarations.c"
#include "other-functions.c"
#include "initialize.c"
#include "input.c"
#include "output.c"
#include "autonomous.c"


task main() {
	initialize(BLUE_S); //Which way does the robot start pointing?
	autoReset(0); // 0 = Start, 1 = Finish
	#include "routine.c"
	autoReset(1);
	for (int j=0; j<10; j++) motor[j]=0;
	while(true) {}
}
