#pragma config(Sensor, in1,    LINE_L,         sensorReflection)
#pragma config(Sensor, in2,    LINE_C,         sensorReflection)
#pragma config(Sensor, in3,    LINE_R,         sensorReflection)
#pragma config(Sensor, in5,    ANGLE_POT,      sensorPotentiometer)
#pragma config(Sensor, in6,    GYRO,           sensorGyro)
#pragma config(Sensor, dgtl1,  QUAD_R,         sensorQuadEncoder)
#pragma config(Sensor, dgtl3,  QUAD_L,         sensorQuadEncoder)
#pragma config(Sensor, dgtl8,  ULTRA,          sensorSONAR_cm)
#pragma config(Sensor, dgtl11, QUAD_SLIDE,     sensorQuadEncoder)
#pragma config(Motor,  port1,           INTAKE,        tmotorVex393HighSpeed, openLoop)
#pragma config(Motor,  port2,           DRIVE_R,       tmotorVex393HighSpeed, openLoop)
#pragma config(Motor,  port3,           DRIVE_L,       tmotorVex393HighSpeed, openLoop, reversed)
#pragma config(Motor,  port4,           ANGLE,         tmotorVex393HighSpeed, openLoop)
#pragma config(Motor,  port5,           SLIDE_L,       tmotorVex393HighSpeed, openLoop)
#pragma config(Motor,  port6,           SLIDE_R,       tmotorVex393HighSpeed, openLoop)
#pragma config(Motor,  port7,           TREAD,         tmotorVex269, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#define   PRACTICE // If not defined, then competition mode
#include "definitions.c"
#include "declarations.c"
#include "other-functions.c"
#include "initialize.c"
#include "input-and-output.c"
#include "autonomous.c"


task main()
	{
	initialize(BLUE_S); //Which way does the robot start pointing?
	autoReset(0); // 0 = Start, 1 = Finish

	#include "routine.c"

	autoReset(1);

	for (int j=0; j<10; j++)
		motor[j]=0;

	while(true) {}
	}
